<div class="footer-info">
	<img src="/pub/static/frontend/Barbaronbg/default/bg_BG/images/logo.svg" alt="Barbaron.bg"/>

	<p><strong>Барбарон БГ</strong></p>
	<p>
		Магазин София<br/>
		бул.Христо Ботев №23
	</p>

	<p class="ttl"><strong>Свържи се с нас</strong></p>
	<p>
		<a href="https://www.facebook.com/beanbags.bg" class="facebook"><i class="fa fa-facebook-square"></i></a>
		<span class="phone"><i class="fa fa-mobile-phone"></i>0897907701</span>
		<span class="phone"><i class="fa fa-phone"></i>02/482-35-36</span>
		<a href="mailto:info@barbaron.bg" class="mail"><i class="fa fa-envelope"></i>info@barbaron.bg</a>
	</p>

</div>