<?php 
    $_products = $this->getProducts();
    $_config = $this->getConfig();
    $_imageWidth = $this->getImageWidth();
?>
<ul class="products list items featured">
    <?php foreach ($_products as $_product): ?>
        <li class="item">
            <a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo">
                <span class="img"><img src="<?php echo $this->getImageHelper()->init($_product, 'product_page_image_featured')->getUrl(); ?>" alt="<?php echo $this->escapeHtml($_product->getName()) ?>" /></span>

                <span class="name"><?php echo $this->escapeHtml($_product->getName()) ?></span>
            </a>
        </li>
    <?php endforeach; ?>
</ul>